- hosts: localhost
  tasks:
  - name: Install VSCode
    homebrew_cask:
      name: visual-studio-code
      state: latest
  - name: Install git
    homebrew:
      name:
        - git
        - go
        - awscli
        - kubectl
        - shellcheck
        - aws-iam-authenticator
      state: latest
